### PR TITLE
Milestone 2: Render missions

### PR DESCRIPTION
**Pull request by mohisa302**
### Render missions
In this milestone I:

- Displayed all the missions 
- Used reducer
- Used useSelector

### CODE REVIEW

**Comment by Ezzywealth** [comment]
# Optional Comments
## Given design
design


## Your design
Screenshot 2023-03-08 090330

-  From your design screenshot, your table is too close to the body of the webpage. I would suggest you give some margin to the table to space it out a bit. Kindly compare with the given design.
- Also the background of the design for `tr` on odd lines shouldn't be the same for the `tr` on even lines. I would suggest you fix that for it to match the given design.
- Finally, the font of the text on the Missions Column on your design should be bold, to match the given design.

**Review by Ezzywealth — APPROVED** [review]
Hi @mohisa302 
image

# Highlights 🟢

- PR is professional 👍
- Linter checks passed ✔️
- Good table design👍
- Good commit message ✔️

# Optional suggestions
N/A

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

#
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Ezzywealth** [comment]
# Optional changes
## Given design
design


## Your design
Screenshot 2023-03-08 090330

-  From your design screenshot, your table is too close to the body of the webpage. I would suggest you give some margin to the table to space it out a bit. Kindly compare with the given design.
- Also the background of the design for `tr` on odd lines shouldn't be the same for the `tr` on even lines. I would suggest you fix that for it to match the given design.
- Finally, the font of the text on the Missions Column on your design should be bold, to match the given design.

**Comment by mohisa302** [comment]
Thanks for your review, I implemented styles in another branch 🙏

**Pull request merged**
