### PR TITLE
Milestone 4: Navbar 

### PR DESCRIPTION
**Pull request by mohisa302**
### Navbar 
In this milestone I:
- Added styles to navbar based on template

### CODE REVIEW

**Review by Ezzywealth — CHANGES_REQUESTED** [review]
Hey @mohisa302 
Good job so far! But there are some changes that needs to be made for your project to meet the project requirements.

#Highlights

- All linters checks passed✔️
- Good commit message ✔️
- Join `Mission button` working properly ✔️

# Required Changes ♻️
Kindly check the comments under the review.

# Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

# 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Ezzywealth** [comment]
missions

- Your design above breaks for mobile devices. I would suggest you add some responsiveness to your styling and also make use of the `Hamburger` menu for mobile navigation. This would make your design accessible

navbar

- The Navbar needs some space to breathe. The elements in the navbar are not centered and this affects the outlook. I would suggest you add some padding to the nav container and center the elements inside the navbar for better aesthetics

**Comment by mohisa302** [comment]
Thanks for your constructive review

**Comment by Ezzywealth** [comment]
Hey @mohisa302 😊,
Good job!
 # STATUS: APPROVED! 🥇 💯
image

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 🚀
Congratulations! 🎉

#Highlights
- All linters checks passed✔️
- Good commit message ✔️
- Navbar design looking great✔️
- Implemented requested changes ✔️

# Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

# 
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
